name = "MyJuliaPkg"
uuid = "4aad55e6-3783-49d8-8c0b-540e9d18c8e0"
authors = ["stefanocovino <stefano.covino@inaf.it> and contributors"]
version = "0.2.2"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
